package obfs4

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config holds obfs4 configuration for both client and server.
type Config struct {
	// Certificate is the base64-encoded obfs4 certificate (client-side).
	Certificate string

	// IATMode controls inter-arrival time obfuscation.
	// 0: disabled (minimal overhead)
	// 1: enabled (standard obfuscation)
	// 2: paranoid (maximum obfuscation, higher overhead)
	IATMode int

	// StateDir is the directory for storing keys and state (server-side).
	StateDir string

	// NodeID is the bridge's node identifier (server-side, optional).
	NodeID []byte

	// PrivateKey is the bridge's private key (server-side, optional).
	PrivateKey []byte
}

// DefaultConfig returns a default obfs4 configuration.
func DefaultConfig() *Config {
	return &Config{
		IATMode: 0, // Disabled by default for performance
	}
}

// GenerateServerKeys generates new obfs4 server keys by launching obfs4proxy.
// Returns the certificate string that should be distributed to clients.
//
// Note: This function launches obfs4proxy which will generate keys in stateDir.
// The obfs4proxy binary must be available on the system.
func GenerateServerKeys(stateDir string) (certificate string, err error) {
	if stateDir == "" {
		return "", fmt.Errorf("state directory is required")
	}

	// Create state directory if it doesn't exist
	if err := os.MkdirAll(stateDir, 0o700); err != nil {
		return "", fmt.Errorf("failed to create state directory: %w", err)
	}

	// Keys are generated automatically by obfs4proxy on first run
	// We'll return an empty string and let the server generate keys on Start()
	return "", fmt.Errorf("keys will be generated by obfs4proxy on first run - use Server.GetCertificate() after Start()")
}

// LoadServerKeys loads existing obfs4 server keys from stateDir.
// Returns the certificate string for distribution.
func LoadServerKeys(stateDir string) (certificate string, err error) {
	if stateDir == "" {
		return "", fmt.Errorf("state directory is required")
	}

	// Read certificate from obfs4_bridgeline.txt
	certFile := filepath.Join(stateDir, "obfs4_bridgeline.txt")
	data, err := os.ReadFile(certFile)
	if err != nil {
		return "", fmt.Errorf("failed to load certificate: %w", err)
	}

	// Extract cert parameter
	certificate, err = extractParam(string(data), "cert=")
	if err != nil {
		return "", fmt.Errorf("failed to extract certificate: %w", err)
	}

	return certificate, nil
}

// GenerateOrLoadServerKeys loads existing keys if available, otherwise waits for generation.
func GenerateOrLoadServerKeys(stateDir string) (certificate string, err error) {
	// Try to load existing keys first
	certificate, err = LoadServerKeys(stateDir)
	if err == nil {
		return certificate, nil
	}

	// Keys don't exist, they'll be generated on server start
	return "", fmt.Errorf("keys not found - they will be generated when server starts")
}

// ValidateCertificate checks if an obfs4 certificate string is valid.
// Certificate format: base64-encoded string
func ValidateCertificate(cert string) error {
	if cert == "" {
		return fmt.Errorf("certificate is empty")
	}

	// Basic validation: check if it's valid base64
	_, err := base64.StdEncoding.DecodeString(cert)
	if err != nil {
		return fmt.Errorf("invalid certificate format: %w", err)
	}

	// Certificates are typically 88 characters (base64 of 64 bytes + padding)
	if len(cert) < 20 {
		return fmt.Errorf("certificate too short: %d characters", len(cert))
	}

	return nil
}

// ParseBridgeLine parses an obfs4 bridge line and extracts the configuration.
// Bridge line format: "obfs4 IP:PORT FINGERPRINT cert=CERT iat-mode=MODE"
func ParseBridgeLine(bridgeLine string) (*Config, string, error) {
	// This is a simplified parser. In production, use the config package's ParseBridge.
	// For now, we'll extract just the cert and iat-mode parameters.

	config := DefaultConfig()

	// Extract cert parameter
	cert, err := extractParam(bridgeLine, "cert=")
	if err != nil {
		return nil, "", fmt.Errorf("failed to extract certificate: %w", err)
	}
	config.Certificate = cert

	// Extract iat-mode parameter (optional)
	iatMode, err := extractParam(bridgeLine, "iat-mode=")
	if err == nil {
		switch iatMode {
		case "0":
			config.IATMode = 0
		case "1":
			config.IATMode = 1
		case "2":
			config.IATMode = 2
		default:
			return nil, "", fmt.Errorf("invalid iat-mode: %s", iatMode)
		}
	}

	// Extract address (IP:PORT)
	address, err := extractAddress(bridgeLine)
	if err != nil {
		return nil, "", fmt.Errorf("failed to extract address: %w", err)
	}

	return config, address, nil
}

// extractParam extracts a parameter value from a bridge line.
func extractParam(line, param string) (string, error) {
	// Find the parameter
	idx := strings.Index(line, param)
	if idx == -1 {
		return "", fmt.Errorf("parameter %s not found", param)
	}

	start := idx + len(param)
	end := start

	// Find the end of the parameter value (space or end of string)
	for end < len(line) && line[end] != ' ' && line[end] != '\n' && line[end] != '\r' {
		end++
	}

	return line[start:end], nil
}

// extractAddress extracts the IP:PORT address from a bridge line.
func extractAddress(line string) (string, error) {
	// Bridge line format: "obfs4 IP:PORT ..." or "Bridge obfs4 IP:PORT ..."
	fields := strings.Fields(line)
	if len(fields) < 2 {
		return "", fmt.Errorf("invalid bridge line format")
	}

	// Handle "Bridge obfs4 IP:PORT" or "obfs4 IP:PORT"
	addressIdx := 1
	if fields[0] == "Bridge" && len(fields) >= 3 {
		addressIdx = 2
	}

	if addressIdx >= len(fields) {
		return "", fmt.Errorf("address not found in bridge line")
	}

	address := fields[addressIdx]

	// Basic validation: should contain a colon
	if !strings.Contains(address, ":") {
		return "", fmt.Errorf("invalid address format: %s", address)
	}

	return address, nil
}

// ExportKeys exports the obfs4 keys to a backup file.
// Note: obfs4proxy manages keys internally. This function copies the state directory.
func ExportKeys(stateDir, outputPath string) error {
	// Read the obfs4 state file
	stateFile := filepath.Join(stateDir, "obfs4_state.json")
	data, err := os.ReadFile(stateFile)
	if err != nil {
		return fmt.Errorf("failed to read state file: %w", err)
	}

	// Write to output
	if err := os.WriteFile(outputPath, data, 0o600); err != nil {
		return fmt.Errorf("failed to write export file: %w", err)
	}

	return nil
}

// ImportKeys imports obfs4 keys from a backup file.
// Note: obfs4proxy manages keys internally. This function copies to the state directory.
func ImportKeys(inputPath, stateDir string) error {
	data, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("failed to read import file: %w", err)
	}

	// Create state directory
	if err := os.MkdirAll(stateDir, 0o700); err != nil {
		return fmt.Errorf("failed to create state directory: %w", err)
	}

	// Write to state file
	stateFile := filepath.Join(stateDir, "obfs4_state.json")
	if err := os.WriteFile(stateFile, data, 0o600); err != nil {
		return fmt.Errorf("failed to save state file: %w", err)
	}

	return nil
}

// GetStateFilePath returns the path to the obfs4 state file.
func GetStateFilePath(stateDir string) string {
	return filepath.Join(stateDir, "obfs4_state.json")
}

// GetBridgeLineExample returns an example bridge line for documentation.
func GetBridgeLineExample(address, cert string, iatMode int) string {
	fingerprint := "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" // Placeholder
	return fmt.Sprintf("Bridge obfs4 %s %s cert=%s iat-mode=%d",
		address, fingerprint, cert, iatMode)
}
